Repository GSA/CHRISUpdate, pull requests merged in 2019-06, with the labels that each got.

#124 Hr cr april 2019
  CHRISUpdate/Data/LoadLookupData.cs
  CHRISUpdate/Data/SaveData.cs
  CHRISUpdate/HRUpdate.csproj
  CHRISUpdate/Lookups/BuildingLookup.cs
  CHRISUpdate/Lookups/Lookup.cs
  CHRISUpdate/Mapping/Constants.cs
  CHRISUpdate/Mapping/EmployeeMapping.cs
  CHRISUpdate/Models/Building.cs
  CHRISUpdate/Models/Investigation.cs
  CHRISUpdate/Utilities/ExtensionMethods.cs
  CHRISUpdate/Validation/ValidateHR.cs
Labels: Change Request

#129 Hr cr april 2019 (Dev to Test)
  CHRISUpdate/App.config
  CHRISUpdate/Data/LoadLookupData.cs
  CHRISUpdate/Data/SaveData.cs
  CHRISUpdate/HRUpdate.csproj
  CHRISUpdate/Lookups/BuildingLookup.cs
  CHRISUpdate/Lookups/Lookup.cs
  CHRISUpdate/Mapping/Constants.cs
  CHRISUpdate/Mapping/EmployeeMapping.cs
  CHRISUpdate/Mapping/SummaryMapping.cs
  CHRISUpdate/Models/Building.cs
  CHRISUpdate/Models/Investigation.cs
  CHRISUpdate/Models/Summary.cs
  CHRISUpdate/Process/ProcessHR.cs
  CHRISUpdate/Process/ProcessSeparation.cs
  CHRISUpdate/Process/ProcessSummary.cs
  CHRISUpdate/Utilities/CSVHelper.cs
  CHRISUpdate/Utilities/EmployeeComparer.cs
  CHRISUpdate/Utilities/ExtensionMethods.cs
  CHRISUpdate/Validation/ValidateHR.cs
  CHRISUpdate/packages.config
Labels: Change Request, merge

#130 Hr cr april 2019 (Test to Master)
  CHRISUpdate/App.config
  CHRISUpdate/Data/LoadLookupData.cs
  CHRISUpdate/Data/SaveData.cs
  CHRISUpdate/HRUpdate.csproj
  CHRISUpdate/Lookups/BuildingLookup.cs
  CHRISUpdate/Lookups/Lookup.cs
  CHRISUpdate/Lookups/StateLookup.cs
  CHRISUpdate/Mapping/Constants.cs
  CHRISUpdate/Mapping/EmployeeMapping.cs
  CHRISUpdate/Mapping/SummaryMapping.cs
  CHRISUpdate/Mapping/TypeConversion.cs
  CHRISUpdate/Models/Building.cs
  CHRISUpdate/Models/Investigation.cs
  CHRISUpdate/Models/Summary.cs
  CHRISUpdate/Process/ProcessHR.cs
  CHRISUpdate/Process/ProcessSeparation.cs
  CHRISUpdate/Process/ProcessSummary.cs
  CHRISUpdate/Program.cs
  CHRISUpdate/Utilities/CSVHelper.cs
  CHRISUpdate/Utilities/EmployeeComparer.cs
  CHRISUpdate/Utilities/ExtensionMethods.cs
  CHRISUpdate/Utilities/Helpers.cs
  CHRISUpdate/Validation/ValidateHR.cs
  CHRISUpdate/packages.config
Labels: merge, pull requests
